version: '3'

vars:

dotenv: ['.env']

tasks:
  default:
    cmds:
    - go run main.go
    silent: true
  db:
    cmds:
      - ./scripts/db-start-docker.sh --name=$DB_DOCKER_NAME --db=$DB_NAME --user=$DB_USER --password=$DB_PWD --port=5432
  dbup:
    cmds:
      - dbmate up
  psql:
    cmds:
      - PGPASSWORD=$DB_PWD psql -h $DB_ADDR -p $DB_PORT -d $DB_NAME -U $DB_USER
