// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.501
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "jirku.sk/zberatel/template/components"
import "github.com/justinas/nosurf"
import "net/http"

type RegisterFormMV struct {
	Username             string `validate:"required,min=3,max=20"`
	Email                string `validate:"required,email"`
	Password             string `validate:"required,min=8,max=64,eqfield=PasswordConfirmation"`
	PasswordConfirmation string
	Token                string `form:"csrf_token" validate:"required"`
	Errors               map[string][]string
	RecaptchaKey         string
}

func NewRegisterFormMV(r *http.Request, recaptcha string) RegisterFormMV {
	return RegisterFormMV{
		Token:        nosurf.Token(r),
		RecaptchaKey: recaptcha,
		Errors:       make(map[string][]string),
	}
}

func (mv *RegisterFormMV) GetError(field string) []string {
	if v, ok := mv.Errors[field]; ok {
		return v
	}
	return []string{}
}

func (mv *RegisterFormMV) IsValid() bool {
	return len(mv.Errors) == 0
}

func (mv *RegisterFormMV) hasRecaptcha() bool {
	return mv.RecaptchaKey != ""
}

func (mv *RegisterFormMV) SetError(field string, err string) {
	if _, ok := mv.Errors[field]; !ok {
		mv.Errors[field] = []string{}
	}
	mv.Errors[field] = append(mv.Errors[field], err)
}

func RegisterForm(mv RegisterFormMV) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"register-form\" class=\"flex flex-col space-y-4\" action=\"/auth/register\" method=\"post\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInput(components.
			NewTextInputMV("Username", "Username").
			WithPlaceholder("Fill in your username").
			WithErrors(mv.GetError("Username")...).
			WithValue(mv.Username)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInput(components.
			NewTextInputMV("Email", "Email").
			WithPlaceholder("Fill in your email").
			WithErrors(mv.GetError("Email")...).
			WithValue(mv.Email)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInput(components.
			NewTextInputMV("Password", "Password").
			WithPlaceholder("Specify the password").
			WithErrors(mv.GetError("Password")...).
			WithType("password")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextInput(components.
			NewTextInputMV("Password Confirmation", "PasswordConfirmation").
			WithType("password").
			WithErrors(mv.GetError("PasswordConfirmation")...).
			WithPlaceholder("Repeat the password")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<input type=\"hidden\" name=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(nosurf.FormFieldName))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(mv.Token))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 = []any{"mt-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded",
			templ.KV("g-recaptcha", mv.hasRecaptcha())}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<input class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ.CSSClasses(templ_7745c5c3_Var2).String()))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if mv.hasRecaptcha() {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" data-sitekey=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(mv.RecaptchaKey))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" data-callback=\"onSubmit\" data-action=\"submit\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" type=\"submit\" value=\"Register\"></form><script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `
	 	function onSubmit(token) {
			document.getElementById("register-form").submit();
		}
	`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><script src=\"https://www.google.com/recaptcha/api.js\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
