// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"jirku.sk/kulektor/ksuid"
)

type Collection struct {
	ID          ksuid.KSUID
	UserID      string
	Title       string
	Description *string
	Type        *string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	BlueprintID interface{}
	IsBlueprint bool
}

type User struct {
	ID        string
	Username  string
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
