// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"

	"jirku.sk/zberatel/model"
)

type Collection struct {
	ID          model.KSUID
	UserID      model.KSUID
	Title       string
	Description sql.NullString
	Type        string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Collector struct {
	ID          model.KSUID
	UserID      model.KSUID
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID              model.KSUID
	Username        string
	Password        string
	Email           string
	EmailVerifiedAt sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type UserToken struct {
	UserID model.KSUID
	Token  model.KSUID
}
